// <auto-generated />
using AVSoftTest.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AVSoftTest.DAL.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AVSoftTest.DAL.Models.CounterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Counters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Key = 1,
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            Key = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 4,
                            Key = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 5,
                            Key = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 6,
                            Key = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 7,
                            Key = 2,
                            Value = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
